config/routes.rb
Rails.application.routes.draw do

  resources :cars do
    resources :test_drives, shallow: true
  end

  get '/cars_order_by_rating' => 'cars#order'

  resources :test_drives, only: [:new]

  resources :users, only: [:show, :new, :create] do
    resources :cars, only: [:index]
  end

  resources :categories

  root 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#google_create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  belongs_to :category
  has_many :test_drives
  has_many :users, through: :test_drives

  validates :name, presence: true, :uniqueness => true
  validates :price, presence: true
  validates :image, presence: true

  scope :sort_by_high_rating, -> {joins(:test_drives).group(:id).order('avg(rating) desc')}

  scope :most_test_drives, -> {joins(:test_drives).group(:id).select('cars.id, count(test_drives.id) as count').order('max(test_drives.id) desc')}
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :cars
end

app/models/test_drive.rb
class TestDrive < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :title, :description, presence: true
  validates :rating, presence: {only_integer: true, in: 1...5}

  validates :car, uniqueness: {scope: :user, message: "You've already tested this car."}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :test_drives
  has_many :cars_test_drives, through: :test_drives
  has_many :cars

  has_secure_password

  validates :username, presence: true
  validates :password, presence: true
  validates :email, presence: true, uniqueness: true 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  private

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def redirect_if_not_logged_in
    redirect_to login_path if !logged_in?
  end

  def able_to_edit?(car)
    car.user == current_user
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]
  before_action :redirect_if_not_logged_in

  def index
    if params[:user_id]
      user = User.find(params[:user_id])
      @cars = user.cars
    else
      @cars = Car.all
    end 
  end

  def order
    @cars = Car.sort_by_high_rating.includes(:test_drives)
    render :index
  end

  def show
    set_car
  end

  def new
    @car = Car.new
  end

  def edit
    if able_to_edit?(@car)
      render :edit
    else
      redirect_to @car
    end
  end

  def create
    @car = Car.new(car_params)
    @car.user_id = session[:user_id]
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end


  def update
    if @car.update(car_params)
      redirect_to @car
    else
      render :edit
    end
  end


  def destroy
    set_car
    @car.destroy
  end

  private
    def set_car
      @car = Car.find(params[:id])
    end

    def car_params
      params.require(:car).permit(:name, :price, :category_id, :image)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :redirect_if_not_logged_in

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(id: params[:id])
  end


  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def welcome
  end

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  def google_create
    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.username = auth['info']['name']
      u.email = auth['info']['email']
      u.password = SecureRandom.hex
    end
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/test_drives_controller.rb
class TestDrivesController < ApplicationController
  before_action :set_test_drive, only: %i[ show update ]
  before_action :redirect_if_not_logged_in

  def index
    if params[:user_id]
      user = User.find(params[:user_id])
      @test_drives = user.test_drives
    else
      @test_drives = TestDrive.all
    end
  end


  def show
    set_test_drive
  end


  def new
    if params[:car_id]
      car = Car.find(params[:car_id])
      @test_drive = car.test_drives.build
    else
      @test_drive = TestDrive.new
    end
  end

  def create
    @test_drive = current_user.test_drives.build(test_drive_params)
    if @test_drive.save
      redirect_to car_path(@test_drive.car_id)
    else
      render :new
    end
  end

  def destroy
    set_test_drive
    @test_drive.destroy
  end

  private

    def set_test_drive
      @test_drive = TestDrive.find(params[:id])
    end

    def test_drive_params
      params.require(:test_drive).permit(:title, :description, :rating, :car_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_not_logged_in, only: %i[ show ]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/test_drives_helper.rb
module TestDrivesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<%= simple_form_for @car do |f| %>
  <%= f.input :name %>
  <br>
  <%= f.input :price %>
  <br>
  <%= f.association :category %>
  <br>
  <%= f.input :image %>
  <br>
  <%= f.button :submit %>
<% end %>

app/views/cars/_show_car.html.erb
<%= image_tag(@car.image, style: "width:400px") %>
<br>
<br>
<h4>$<%= @car.price %></h4>
<br>
<br>
<% @car.test_drives.each do |t| %>
<h3><%= t.title %></h3>
<br>
<p><%= t.description %></p>
<br>
<h4>Rating: <%= t.rating %></h4>
<br>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Cars</h1>

<ul>
    <% @cars.map do |car| %>
    <div class="list">
        <h3><%= car.name %></h3>
        <br>
        <li><%= image_tag(car.image, width: 400) %></li>
        <br>
        <h4>$<%= car.price %></h4>
        <br>
        <li><%= link_to 'Show', car %></li>
        <li><%= link_to 'Edit Car', edit_car_path(car) %></li>
        <br>
        <br>
    </div>
    <% end %>
</ul>

<br>
<%= link_to 'Order by Test Drive Rating', cars_order_by_rating_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<h1><%= @car.name %></h1>

<%= render 'show_car' %>

<strong><%= link_to 'Add Test Drive', new_car_test_drive_path(@car) %></strong> | 
<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %> |

app/views/categories/index.html.erb
<h1>Categories</h1>
<br>
<% @categories.each do |c| %>
| <%= link_to "#{c.name}", category_path(c) %> | 
<% end %>

app/views/categories/show.html.erb
<h2><%= @category.name %>'s</h2>

<% @category.cars.each do |car| %>
<div class="list">
    <h3><%= car.name %></h3>
    <br>
    <li><%= image_tag(car.image, style: "width:400px") %></li>
    <br>
    <h4>$<%= car.price %></h4>
    <br>
    <li><%= link_to 'Show', car %></li>
    <li><%= link_to 'Edit Car', edit_car_path(car) %></li>
    <br>
    <br>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarShopperApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'main',%>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/cars.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />

    <title></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag "main" %>
  </head>
  <body>
    <div class="wrapper">
      <a><%= link_to "New Car", new_car_path %> | <%= link_to "View All Cars", cars_path %> | <%= link_to "New Test Drive", new_test_drive_path %> | <%= link_to "View Profile", user_path(session[:user_id]) %> |   <%= link_to "View All Categories", categories_path %> <a/>

        <%= yield %>

      <footer class="branding">
        <a><%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
        <input type=submit value='logout'>
        <% end %></a>
        <br>
        <small>&copy; 2021 <strong>Car Shopper</strong></small>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/categories.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />

    <title></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag "main" %>
  </head>
  <body>
    <div class="wrapper">
      <a><%= link_to "New Car", new_car_path %> | <%= link_to "View All Cars", cars_path %> | <%= link_to "New Test Drive", new_test_drive_path %> | <%= link_to "View Profile", user_path(session[:user_id]) %><a/>

        <%= yield %>

      <footer class="branding">
        <a><%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
        <input type=submit value='logout'>
        <% end %></a>
        <br>
        <small>&copy; 2021 <strong>Car Shopper</strong></small>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />

    <title></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag "main" %>
  </head>
  <body>
    <div class="wrapper">
    

        <%= yield %>

      <footer class="branding">
        <br>
        <small>&copy; 2021 <strong>Car Shopper</strong></small>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/test_drive.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />

    <title></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag "main" %>
  </head>
  <body>
    <div class="wrapper">
      <a><%= link_to "New Car", new_car_path %> | <%= link_to "New Test Drive", new_test_drive_path %> | <%= link_to "Logout", logout_path %></a>

        <%= yield %>

      <footer class="branding">
        <small>&copy; 2021 <strong>Car Shopper</strong></small>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/test_drives.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />

    <title></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag "main" %>
  </head>
  <body>
    <div class="wrapper">
      <a><%= link_to "New Car", new_car_path %> | <%= link_to "View All Cars", cars_path %> | <%= link_to "View Profile", user_path(session[:user_id]) %> </a>

        <%= yield %>

      <footer class="branding">
        <a><%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
        <input type=submit value='logout'>
        <% end %></a>
        <br>
        <small>&copy; 2021 <strong>Car Shopper</strong></small>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />

    <title></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag "main" %>
  </head>
  <body>
    <div class="wrapper">
      <a><%= link_to "New Car", new_car_path %> | <%= link_to "View All Cars", cars_path %> | <%= link_to "New Test Drive", new_test_drive_path %> |   <%= link_to "View All Categories", categories_path %> </a>


        <%= yield %>

      <footer class="branding">
        <a><%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
        <input type=submit value='logout'>
        <% end %></a>
        <br>
        <small>&copy; 2021 <strong>Car Shopper</strong></small>
      </footer>
    </div>
  </body>
</html>

app/views/test_drives/_form.html.erb
<%= simple_form_for @test_drive do |f| %>
  <br>
  <%= f.association :car, label_method: :name, value_method: :id %>
  <br>
  <%= f.input :title %>
  <br>
  <%= f.input :description, as: :text %>
  <br>
  <%= f.input :rating, in: 1..5 %>
  <br>
  <%= f.submit %>
<% end %>

app/views/test_drives/edit.html.erb
<h1>Editing Test Drive</h1>

<%= render 'form', test_drive: @test_drive %>

app/views/test_drives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Test Drives</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_drives.each do |test_drive| %>
      <tr>
        <td><%=  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/test_drives/new.html.erb
<h1>New Test Drive</h1>

<%= render 'form', test_drive: @test_drive %>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :username%>
  <%= f.input :email %>
  <%= f.input :password%> 
  <%= f.button :submit %>
<% end %>

app/views/users/_show_cars.html.erb
<% @user.cars.map do |car| %>
<div class="list">
  <br>
    <h4><%= car.name %></h4>
  <br>
  <br>
    <%= image_tag(car.image, width: 400, class: 'd-block mx-auto')%>
  <br>
  <br>
    <h5><%="$#{car.price}"%></h5>
  <br>
  <br>
    <strong><%= link_to "View Car", car %>
      <br>
      <br>
      <br>
  </div>
<%end%>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1><%=@user.username%>'s page</h1>
<br>
<h2>Your Cars</h2>
  <p><%= link_to "view users cars", user_cars_path(@user)%></p>
<br>
<br>
  <ul>
    <li><%= render 'show_cars' %></li>
  </ul>